# list of meta tags
- name: keywords
  content: Webifier, Deployment, Github Pages, Documentation
- name: author
  content: Webifier
- name: viewport
  content: 'width=device-width, initial-scale=1.0'
